### ISSUE TITLE
Error: Could not find or load main class Main

### ISSUE THREAD

**Issue by cherchyk** [heroku/java-getting-started#17]
Hi, I'm following https://devcenter.heroku.com/articles/getting-started-with-java#run-the-app-locally
and at 'heroku local web' I have this error.

admin@DESKTOP-O8G746S /C/Bohdan/dev/java-getting-started (master)
$ heroku local web
forego | starting web.1 on port 5000
web.1  | Error: Could not find or load main class Main                                                          

Does this error related to project structure?

**Comment by sanarroya** [comment]
Hi, I think you already solved this but i had the same error and it was being caused because I had the main class inside a custom package not the ```<default package>```. I tried changing the procfile but it didn't work so in the IDE (Netbeans in my case) I dragged the Main class from inside the custom package to the source package and Netbeans put it inside a ```<default package>``` automatically, and the problem was solved, hope this helps anybody

**Comment by jonmountjoy** [comment]
Did you follow the [previous step](https://devcenter.heroku.com/articles/getting-started-with-java#declare-app-dependencies)?

In particular, have you run `mvn install`. 

Without compiling the code, you won't have a Main class to run.

**Comment by sanarroya** [comment]
Yes I run ```mvn install``` and it didn't work, the only thing that worked was what i mentioned above

**Comment by jonmountjoy** [comment]
What do you mean by "it didn't work"?  Can you show the logs, of what happened when you ran `mvn install`?   Thanks.
